{
  "openapi": "3.0.1",
  "info": {
    "title": "Lab 09 API",
    "description": "Random as heck API",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/"
    }
  ],
  "paths": {
    "/categories": {
      "get": {
        "description": "Get all categories",
        "responses": {
          "200": {
            "description": "Returned a list of categories",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/CategoryList"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new category",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewCategory"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returned the created category",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Category"
                }
              }
            }
          }
        }
      }
    },
    "/categories/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "description": "Get One Category",
        "responses": {
          "200": {
            "description": "Returned one category",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Category"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Delete One Category",
        "responses": {
          "200": {
            "description": "Deleted one category",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Delete"
                }
              }
            }
          }
        }
      },
      "put": {
        "description": "Replace a category",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Category"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returned the updated category",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Category"
                }
              }
            }
          }
        }
      }
    },    
    
    "/teams": {
      "get": {
        "description": "Get all teams",
        "responses": {
          "200": {
            "description": "Returned a list of teams",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/TeamList"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new Team",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewTeam"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returned the created team",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Team"
                }
              }
            }
          }
        }
      }
    },
    "/team/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "description": "Get One Category",
        "responses": {
          "200": {
            "description": "Returned one category",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Category"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Delete One Category",
        "responses": {
          "200": {
            "description": "Deleted one category",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Delete"
                }
              }
            }
          }
        }
      },
      "put": {
        "description": "Replace a category",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Category"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returned the updated category",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Category"
                }
              }
            }
          }
        }
      }
    },
    
    "/players": {
      "get": {
        "description": "Get all players",
        "responses": {
          "200": {
            "description": "Returned a list of players",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/PlayersList"
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Create a new player",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/NewPlayer"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returned the created Player",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Player"
                }
              }
            }
          }
        }
      }
    },
    "/Players/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer"
          }
        }
      ],
      "get": {
        "description": "Get One player",
        "responses": {
          "200": {
            "description": "Returned one player",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Player"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Delete One player",
        "responses": {
          "200": {
            "description": "Deleted one player",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Delete"
                }
              }
            }
          }
        }
      },
      "put": {
        "description": "Replace a player",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Player"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Returned the updated Player",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Player"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CategoryList": {
        "type": "array",
        "example": [
          {
            "id": 1,
            "name": "Category 1"
          },
          {
            "id": 2,
            "name": "Category 2"
          }
        ]
      },
      "NewCategory": {
        "type": "object",
        "example": {
          "name": "Category Name"
        }
      },
      "Category": {
        "type": "object",
        "example": {
          "id": 2,
          "name": "Category Name"
        }
      },
      "Delete": {
        "type": "object",
        "example": {}
      },
      "TeamList": {
        "type": "array",
        "example": [
          {
            "id": 1,
            "name": "Team 1",
            "ref": "players",
            "localField": "name",
            "foreignField": "team",
            "justOne":false
          },
          {
            "id": 2,
            "name": "Team 2",
            "ref": "players",
            "localField": "name",
            "foreignField": "team",
            "justOne":false
          }
        ]
      },
      "NewTeam": {
        "type": "object",
        "example": {
            "name": "Team 1",
              "ref": "players",
              "localField": "name",
              "foreignField": "team",
              "justOne":false
          }
      },
      "Team": {
        "type": "object",
        "example": {
            "id": 1,
            "name": "Category 1",
              "ref": "players",
              "localField": "name",
              "foreignField": "team",
              "justOne":false
          }
      },
      "PlayersList": {
        "type": "array",
        "example": [
          {
            "id": 1,
            "name": "Player 1",
            "position": "P",
            "throws": "R",
            "bats": "L",
            "team": "Team 1"
          },
          {
            "id": 2,
            "name": "Player 2",
            "position": "LF",
            "throws": "R",
            "bats": "R",
            "team": "Team 2"
          }
        ]
      },
      "NewPlayer": {
        "type": "object",
        "example": {
            "name": "Player 1",
            "position": "P",
            "throws": "R",
            "bats": "L",
            "team": "Team 1"
          }
      },
      "Player": {
        "type": "object",
        "example": {
            "id": 1,
            "name": "Player 1",
            "position": "P",
            "throws": "R",
            "bats": "L",
            "team": "Team 1"
          }
      }

    }
  }
}